.eleventy.js
src/_includes/layouts/project.liquid
src/projects/Berliner-Badestellen.md
src/projects/Bikesharing-Scripts.md
src/projects/Kita-Suche.md
src/projects/Mein-Berlin.md
src/projects/Shared-Mobility-Flows.md
src/projects/breitband.md
src/projects/giessdenkiez.md

This PR prepares the project page to display metadata such as repo, languages, etc. in a table format

feat(OSR-66): project data table

---

src/404.md
src/_includes/layouts/project.liquid
src/assets/css/style.css
src/documents/index.liquid
src/projects/index.njk
src/tag.njk

This PR creates some basic tag pages that can be accessed via the tags on each project's detail page.

feat(OSR-36): create basic tag pages

---

.eleventy.js
package.json
tailwind.config.js

This PR updates the scripts so that all style changes are being watched and 11ty rebuilds, including changes in the main CSS file and the Tailwind config file.

fix(Tailwind): watch all style changes

---

utils/fetchGithubData.ts
utils/requests.ts

refactor: use ESM + async/await in utils

---

src/_includes/partials/project-card.liquid
src/_includes/partials/project-overview.liquid
src/tag.liquid
tailwind.config.js

This PR adds the `updated_at` field of a project (if available) to the project cards.

feat(OSR-75): include updated_at in cards (+ styling)

---

src/projects/Mein-Berlin.md
src/projects/breitband.md

fix(tags): capitalize and fix typo

---

src/_includes/layouts/home.liquid
src/_includes/layouts/wrapper.liquid
src/_includes/partials/header.liquid
src/_includes/partials/nav.liquid
src/assets/images/bg_default.svg

This PR improves the header and nav on small screens.
- the header scrolls
- font-size now responsive

feat(OSR-92): responsive nav

---

package-lock.json
src/contribute.liquid

Maintenance PR

---

src/_includes/partials/contribute-intro.liquid
src/_includes/partials/footer.liquid

This PR updates the contact email address.

chore(OSR-116): update contact email

---

src/projects/Berliner-Badestellen.md
src/projects/Shared-Mobility-Flows.md
src/projects/breitband.md
src/projects/giessdenkiez.md
src/projects/validator.md

https://citylab.atlassian.net/jira/software/projects/OSR/boards/20?selectedIssue=OSR-81
Adds the three agreed-upon headers (Zusammenfassung, Beschreibung des Projekts, Weitere Informationen) to each page. A few pages require more work to bring them into compliance with our content guidelines; I've made separate issues for those in Jira.

standardizing project pages

---

src/projects/giessdenkiez.md
src/projects/validator.md

Just made two small changes to two of the project pages

small stylistic fixes

---

src/projects/Shared-Mobility-Flows.md

Re-wrote the project page for Shared Mobility to better reflect the project and bring it into agreement with our content guidelines. Would be great if @inesweigand could review the text.

Re-write of shared mobility project page

---

src/_includes/partials/footer.liquid
src/_includes/partials/logos.liquid

This PR updates the footer so that it uses the TSB style.

feat(OSR-144): use TSB footer

---

src/_includes/layouts/project.liquid
src/_includes/layouts/wrapper.liquid
src/_includes/partials/breadcrumbs.liquid
src/_includes/partials/footer.liquid

This PR implements the breadcrumb functionality for 2nd level pages and also for 3rd level project pages.

feat: OSR-127: breadcrumbs

---

src/projects/Shared-Mobility-Flows.md

**Important**: Please create your Pull Request against the `staging` branch (not `main`).
Please add a short summary of your changes and ideally reference GitHub issues, Jira tickets etc. below. Then delete these instructions.
---

Fixing Typos and Spelling

---

src/_includes/layouts/root.liquid
src/_includes/partials/submit-project-button.liquid
tailwind.config.js

This PR updates the style of the submit-project-button to make it more visible and be more user-friendly. Thanks for the suggestions @edgalindo

style: make project button more visible

---

src/projects/Kita-Suche.md

Re-wrote the project page for Kita-Suche to conform to our contribution guidelines.

rewrite kita-suche project page

---

src/projects/Berliner-Badestellen.md
src/projects/Kita-Suche.md
src/projects/Mein-Berlin.md
src/projects/Shared-Mobility-Flows.md
src/projects/breitband.md
src/projects/giessdenkiez.md
src/projects/kunst_pankow.md
src/projects/validator.md

This PR applies the new tags as defined by @inesweigand to the projects.
PR #129 was closed in favour of this PR as there were some sync issues with `main` that were easier to fix with this new branch/PR.

feat(OSR-126): apply new tag selection

---

src/projects/Mein-Berlin.md

Minor edit adjusting the "Institution" field per the project owner's wishes.

Mein Berlin minor edit

---

src/_includes/layouts/home.liquid
src/_includes/partials/project-card.liquid
src/_includes/partials/project-overview.liquid
tailwind.config.js

To handle long project titles better.

style(project grid): refine columns and rows

---

src/projects/Berliner-Badestellen.md

replaced link with https://badestellen.netlify.app/ as suggested by Seb Meier

changed url for badestellen

---

.github/renovate.json

chore(renovate): use main as base branch

---

src/projects/machtsprache.md

chore: fix addition date for macht.sprache.

---

netlify.toml

Not extremely urgent because of the static nature of the site, but just to have some defaults present.

build(Netlify): add basic security headers

---

netlify.toml

build(Netlify): remove security headers for now

---

cypress/integration/homepage.spec.js
cypress/integration/projects.spec.js
src/_includes/partials/project-card.liquid
src/_includes/partials/tag.liquid
src/index.md

This PR adds a few more Cypress tests for the homepage and for the project overview page.

test(OSR-101, OSR-103): test more elements

---

src/_includes/partials/header.liquid

To prevent the nav's horizontal position from shifting

style(OSR-155): allocate fixed width to TSB icon

---

src/_includes/layouts/root.liquid

chore: update Matomo settings

---

src/projects/giessdenkiez.md

++ updated current number of trees from 625k to 750k

changed number of trees to 750k

---

src/_includes/layouts/root.liquid
src/assets/js/matomo.js

This PR adds a reasonably locked-down Content Security Policy to limit potential vulnerabilities by future changes.

feat(OSR-156): add CSP

---

.github/workflows/build.yml

chore: change from deprecated output command
